name:                gogame
version:             0.1.0.0
github:              "githubuser/assignment1"
license:             BSD3
author:              "Øystein Qvigstad"
maintainer:          "oysteinq@stud.ntnu.no"
copyright:           "2023 Qvigstad"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Education

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/marni/gogame#readme>

dependencies:
- base >= 4.7 && < 5
- text
- sdl2
- sdl2-ttf
- sdl2-image
- monad-loops

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  gogame-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gogame

tests:
  gogame-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - gogame
    - doctest
    - hspec
